/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_tool_NativeMethod */

#ifndef _Included_com_redknot_tool_NativeMethod
#define _Included_com_redknot_tool_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_tool_NativeMethod
 * Method:    initialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_redknot_tool_NativeMethod_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_redknot_tool_NativeMethod
 * Method:    drawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_redknot_tool_NativeMethod_drawFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
